<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Api\Api.csproj" />
    <ProjectReference Include="..\..\src\Database\Database.csproj" />
    <ProjectReference Include="..\..\src\Entities\Entities.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Defra.Lis.Postgres" VersionOverride="0.0.3" />
    <PackageReference Include="Moq" VersionOverride="4.20.72" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" VersionOverride="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" VersionOverride="10.0.11" />
  </ItemGroup>
</Project>
