### Get Cattle for Holding (using environment variable)
GET {{host}}/holdings/{{cph}}/cattle
Accept: application/json

> ../Asserts/Should_be_200_OK.js

### Get Cattle for Holding (explicit CPH)
GET {{host}}/holdings/12/345/6789/cattle
Accept: application/json

> ../Asserts/Should_be_200_OK.js

### Get Bundles for Holding (using environment variable)
GET {{host}}/holdings/{{cph}}/bundles
Accept: application/json

> ../Asserts/Should_be_200_OK.js

### Get Bundles for Holding (explicit CPH)
GET {{host}}/holdings/12/345/6789/bundles
Accept: application/json

> ../Asserts/Should_be_200_OK.js

### Create Registration Bundle
POST {{host}}/registrations
Content-Type: application/json
Accept: application/json

{
  "clientReference": "REG-MNBX4Q2A",
  "holding": {
    "cph": "10/081/1234"
  },
  "animals": [
    {
      "earTag": "UK 12 3456 100003",
      "dateOfBirth": "2026-02-01",
      "sex": "female",
      "breed": "Aberdeen Angus",
      "dam": {
        "type": "surrogate",
        "geneticDamEarTag": "UK 12 3456 000002",
        "surrogateDamEarTag": "UK 12 3456 000003"
      },
      "sire": {
        "earTag": "UK 12 3456 000010",
        "name": "Example sire"
      }
    }
  ]
}

> ../Asserts/Should_be_201_created.js

###